### ISSUE TITLE
Disable grpc warnings on launcher startup

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#128]
The launcher currently logs some asp.net grpc warnings on startup. These are uneccesary and we should either fix the cause of those or disable/hide them.

**Comment by pawelvds** [comment]
Do we have any scenario/steps to reproduce it? I've tried but I did not manage to find it :< 
or maybe we have more info about that would be great @mijomilicevic or @volllly

**Comment by volllly** [comment]
Here's a screenshot of the warnings occuring.

![Image](https://github.com/fiskaltrust/middleware-launcher/assets/24523184/4ca861d8-02a0-4f12-b625-d974c6ac0dc7)
