### ISSUE TITLE
Error installing launcher twice

### ISSUE THREAD

**Issue by LeilaZarban** [fiskaltrust/middleware-launcher#139]
## Background

When a user on linux installs the launcher 2 times (`sudo ./fiskaltrust.Launcher install`), they get the following error.

![Image](https://github.com/fiskaltrust/middleware-launcher/assets/67684543/e5d07eee-3230-43cf-a16a-5a7a96ae92d1)

## Problem

When writing to the systemd unit file `/etc/systemd/system/*.service` we append. This leads to the file being invalid.

## Solution

We should not append to the systemd unit file but overwrite it.

Before installing the launcher service we should check if the launcher is already installed (by checking if the file exists _and_ by [using systemd](https://unix.stackexchange.com/a/751787)) and fail the installation in this case with nice error messages (in the error message we can tell them to run the `uninstall` command, if that actually solves the problem).

In the `uninstall` command we should make sure that we actually remove the file and that that is enough to really remove the service from systemd.

**Comment by forsthug** [comment]
The systemd service is never fully running at the moment, it suddenly stops. It seems the lifetime solution is not working. Maybe we should consider this implementation https://devblogs.microsoft.com/dotnet/net-core-and-systemd/
