### ISSUE TITLE
Architectural corner stones

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/middleware-launcher#2]
### User story
_As maintainers of the Middleware Launcher, we want to clarify the components and high-level architecture together, so that we can start developing a first prototype._

### Context
Before starting the first prototype, we'd like to clarify the corner stones of the upcoming Middleware Launcher. This should include:

- [ ] Proposed components
- [ ] Architectural principles
- [ ] Technology to use

**Comment by volllly** [comment]
![Launcher Architecture drawio](https://user-images.githubusercontent.com/24523184/140906731-730d6bae-7f20-4c3e-bad4-5253f61e43ee.png)
