### ISSUE TITLE
Service folder

### ISSUE THREAD

**Issue by TSchmiedlechner** [fiskaltrust/middleware-launcher#3]
### User story
_As a user of the Middleware Launcher, I want the Middleware's default service directory to be located in a common place, so that I can install the Launcher on all relevant OSs._

### Context
The _service folder_ is the directory that's used by the Launcher to store packages, configuration, databases and other installation-specific data. In the 'old' Middleware Launcher, we used `C:\ProgramData\fiskaltrust\` on Windows `/usr/share/fiskaltrust/` on Unix as the default values for this directory. Especially the latter has become problematic, as it's a non-accessible path per default in newer macOS versions.

We should define defaults for this critical directory that work on all modern operating systems.

**Comment by volllly** [comment]
According to the  [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) the the correct linux folder is `/var/lib/fiskaltrust`.

Windows should still be `C:/ProgramData/fiskaltrust`.

MacOS should be `/Library/Application Support` but this needs admin access during installation. AFAIKT there's no workaround for global installation.

**Comment by volllly** [comment]
cb9d1bfd6d133d76f278700aac88a83f20027fac
