### ISSUE TITLE
Detect failed self update and rollback if failed

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#53]
If the self-update fails, the launcher should be able to recover.

**Comment by volllly** [comment]
@StefanKert did we understand this correctly? 😁

**Comment by StefanKert** [comment]
Yep, this is the interesting part when it comes to updating the launcher. In fact we should think about how we can make sure that we counter the risk of a broken installation of an update and if there are still atomic steps involved that can lead to a state that is unrecoverable, how can we notice that in a scaled way and how can we rollback the faulty update.

**Comment by volllly** [comment]
We have 2 cases I think:

1. The update process fails, and the installation is broken.
    > Maybe solved by not overwriting the launcher executable but backing up (renaming) the old executable and then moving the new one. We can then check the executable hash or sth like that and rollback to the backup if it's different.

2. The update process fails but the updated executable is faulty (e.g. contains a bug or does not work on the system for some reason)
    > I don't think we can recover from this case. We would need the updater to run and check the launcher which is (I think) not really possible when running the launcher as a service because the update happens on system shutdown.

**Comment by StefanKert** [comment]
> Maybe solved by not overwriting the launcher executable but backing up (renaming) the old executable and then moving the new one. We can then check the executable hash or sth like that and rollback to the backup if it's different.

That sounds reasonbale. So the rename would be the last action that we can perform and it should probably be also the last step so that we can recover in case the laucherupdate crashes in between. So similar to enabling a Feature Flag right?

> I don't think we can recover from this case. We would need the updater to run and check the launcher which is (I think) not really possible when running the launcher as a service because the update happens on system shutdown.

Do we have something like --dry-run?

**Comment by volllly** [comment]
> So similar to enabling a Feature Flag right?

I'm not sure I understand 😅

> Do we have something like --dry-run?

No, but I see how that would be helpful in this situation.

Another thing that could lead to problems though is that currently we do the update on service shutdown (= system shutdown). If we take too long to check the validity the user/os might force shutdown and interrupt the update process.
