### ISSUE TITLE
Doubleclicking the launcher executable should run launcher

### ISSUE THREAD

**Issue by forsthug** [fiskaltrust/middleware-launcher#77]
when i download the launcher i want to start by excuting the file without searching cb and at as they are in the config file

**Comment by volllly** [comment]
**Proposed solution:** when doubleclicking/opening the `fiskaltrust.Launcher` executable should default to using the `run` command.

**Comment by mijomilicevic** [comment]
When implementing this, we should also update System.CommandLine to the newest version. Maybe we can also think about switching to another package.

**Comment by volllly** [comment]
We should also add install and uninstall scripts to configuration service.
