### ISSUE TITLE
Allow portsharing on Windows

### ISSUE THREAD

**Issue by mijomilicevic** [fiskaltrust/middleware-launcher#78]
I am trying to run two Middleware instances with Launcher 2.0 at the same time and want to use the same port with another subdirectory for the two configured Queue's/SCU's as it was possible with launcher 1.3. 
e.g.:
Queue1 -> http://localhost:1500/fiskaltrust1
Queue2 -> http://localhost:1500/fiskaltrust2

I want to be able to host two Queue's/SCU's on one machine as described in the example above.

The reason for that is that a lot of our partners are using such configurations and they were working with launcher 1.3.

**Comment by volllly** [comment]
We should also check that binding to an ip address or domain is working properly. And that the handling of the url path is done correctly.
