### ISSUE TITLE
Windows defender warning - Publisher unknown

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware-launcher#92]
In the current version (-rc5) of the Launcher I am getting the following warning when starting the Launcher. It looks like this is due to the fact that the publisher is unknown.

![image](https://github.com/fiskaltrust/middleware-launcher/assets/7176615/fc40eed8-928f-4078-a7d7-349e6ce707f4)

**Comment by mijomilicevic** [comment]
This one should be solved by adding code signing to the Launcher 2.0 build pipeline.

**Comment by volllly** [comment]
In the process we should also already move the launcher pipelines to github actions.
