### ISSUE TITLE
Print version number of packages while starting up 

### ISSUE THREAD

**Issue by StefanKert** [fiskaltrust/middleware-launcher#96]
Right now we are not printing the package version when debugging. IMO it would be helpful to see the version that is currently running while starting up.

![image](https://github.com/fiskaltrust/middleware-launcher/assets/7176615/85bc1cb1-378a-4379-9576-a9ba524a5c68)

**Comment by volllly** [comment]
This is normally already done.
In this case the package crashes before it can log its version. That means something is crashing in the launcher not the SCU.

This will be improved by #97.
