### ISSUE TITLE
Allow dynamic port for LauncherPort

### ISSUE THREAD

**Issue by volllly** [fiskaltrust/middleware-launcher#98]
Right now the `LauncherPort` is configured in the configuration. If this port is not free the launcher cannot start.

Error handling in this case is very bad at the moment and needs to be improved.

Also we should add a way for the launcher to choose its own port.

This could for example be achieved by allowing the port to be set to 0 and have the the launcher get a port assigned by the os.

Another solution is to have the launcher count up from the configured port until it finds an open port.

The solution should possibly prevent the launcher from taking a port that is used by a queue, scu or helper package.

**Comment by TSchmiedlechner** [comment]
Nice ideas, i totally agree we need to improve that :+1:

Using gRPC via Unix sockets (where supported) could also be a nice way of omitting port binding on mode n OSs: https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-uds?view=aspnetcore-7.0

**Comment by mijomilicevic** [comment]
Another possibility would be to use named or unamed pipes
